modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "ait"
version = "${version}"
displayName = "Adventures In Time"
authors = "AmbleLabs, Loqor, DrTheo, Duzo"
description = '''
Adventures In Time for 1.21.1, Fabric and Forge!
'''
#logoFile = ""

[[dependencies.ait]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ait]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.liquor]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
